spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  eureka:
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
      service-url:
        defaultZone: http://servicio-eureka-server:8761/eureka



server:
  port: ${PORT:0}

config:
  security:
    oauth:
      client:
        id: frontendapp
        secret: 12345
      jwt:
        key: algun_codigo_secreto_aeiou
  

springdoc:
  api-docs:
    path: /swagger-doc/v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-doc/swagger-ui.html

management:
  tracing:
    enabled: false
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: https://zipkin-trace.onrender.com
      
security:
  jwt:
    secret-key: QnJ5YW06Q2h1Y2h1Y2E=
