spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MarketHubDB
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true



server:
  port: ${PORT:0}
  
  

springdoc:
  api-docs:
    path: /swagger-doc/v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-doc/swagger-ui.html

management:
  tracing:
    enabled: false
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus
  zipkin:
    tracing:
      endpoint: https://zipkin-trace.onrender.com
