spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MarketHubDB
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver


server:
  port: ${PORT:0}
  
  

springdoc:
  api-docs:
    path: /swagger-doc/v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
